---
title: "Mahdi Salim SAIB"
author: Mahdi SALIM SAIB
date: "`r Sys.Date()`"
output:
  pagedown::html_resume:
    css: ['css/styles.css', 'resume']
    # set it to true for a self-contained HTML page but it'll take longer to render
    self_contained: TRUE
    Knit: pagedown::chrome_print("Mahdi_CV.html", format = "pdf", verbose = 2)
---

```{css, echo=FALSE}
.pagedjs_page:not(:first-of-type) {
  --sidebar-width: 0rem;
  --sidebar-background-color: #ffffff;
  --main-width: calc(var(--content-width) - var(--sidebar-width));
  --decorator-horizontal-margin: 0.4in;
}
```

```{css, echo=FALSE}
.date {
  --decorator-horizontal-margin: 0.1in;
  max-width: var(-date-block-width);
}
.date span {
  text-align: center;
}
.date span:nth-child(2)::before {
  right: 0.1in;
}
```

# Aside

## Contact Info {#contact}

-   <i class="fa fa-envelope"></i> [saib.mahdi.s\@gmail.com](mailto:saib.mahdi.s@gmail.com){.email}
-   <i class="fa fa-linkedin"></i> [linkedin.com/MS.SAIB](https://www.linkedin.com/in/mahdi-salim-saib-bb1764b2/?originalSubdomain=fr)
-   <i class="fa fa-ResearchGate"></i> [ResearchGate/MS.SAIB](https://www.researchgate.net/profile/Mahdi_Salim_Saib)
-   <i class="fa fa-phone"></i> (+33) 07 68 21 32 18
-   Pour plus d'information, s'il vous plait, contactez moi par mail.

## Centres d'intérêt {#skills}

-   <i class="fa fa-book-open"></i> Enseignement
-   <i class="fa fa-book-open"></i> Système National des Données de Santé (**SNDS)**
-   <i class="fa fa-book-open"></i> Vulgarisation des concepts de base en épidémiologie, et de l'utilisation de [R](https://rpubs.com/mahdi/602646)
-   <i class="fa fa-book-open"></i> Data-sciences
-   <i class="fa fa-book-open"></i> Santé-publique
-   <i class="fa fa-book-open"></i> Santé-environnement

## Outils utilisés {#Outils}

-   <i class="fa fa-wrench" aria-hidden="true"></i> **Statistiques** : R, R shiny, R Markdown SPSS, WinBUGS, SPAD, SAS

-   <i class="fa fa-wrench" aria-hidden="true"></i> **SIG** : Geodata, Spacestat, GWR4, ArcGIS SavGIS (épidémiologie), MapInfo, QGIS

-   <i class="fa fa-wrench" aria-hidden="true"></i> **Outil usuel** : Excel, Access, Word, Power Point.

-   <i class="fa fa-wrench" aria-hidden="true"></i> **Anglais** : Ecrit, lu, parlé

## AUTRES FORMATIONS {#Formation}

-   <i class="fa fa-eye"></i> Utilisation des données du **SNDS (** DCIR Simplifié -- DCIR, PMSI,...)

-   <i class="fa fa-eye"></i> Gestion de **Projets Complexes** (Ecole Nationale d'Administration)

-   <i class="fa fa-eye"></i> Frontiers in **Spatial Epidemiology** (Kingston University London)

-   <i class="fa fa-eye"></i> Programmer en R pour la **Data Science** de A à Z

# Main

## Mahdi Salim SAIB {#title}

## Education {data-icon="graduation-cap" data-concise="true"}

### Université de Picardie Jules Vernes (UPJV)- Ecole Doctorale Sciences, Technologie et Santé

**Doctorat** : Biologie-Santé / Santé-Publique

Amiens, FRANCE

2015

### Université Joseph Fourier (UJF)

**Master 2** : Méthodologie de recherche en environnement-santé

Grenoble, FRANCE

2011

### Université Joseph Fourier (UJF)

**Master 1** : Ingénierie sante

Grenoble, FRANCE

2010

### Université Ibn Khaldoun - Facultés des sciences agronomiques et vétérinaires

**Médecin Vétérinaire**

Tiaret, ALGERIE

2007

## Expérience professionnelle {data-icon="suitcase"}

### Chargé d'enseignement

Conservatoire national des arts et métiers (CNAM)

Paris, FRANCE

Avr 2019 - à ce jour

-   Des enjeux aux méthodes : modélisation et analyse statistique des données spatialisées de santé

### Sous-directeur des études

Observatoire régional de la santé et du social (OR2S)

Normandie, FRANCE

Avr 2020 - Dec 2020

-   Assistance à l'analyse des données de santé
-   Mise en place d'un tableau de bord de suivi l'état de santé
-   Coordination et supervision des travaux des chargés d'études et des stagiaires.

### Epidémiologiste

Agence Régionale de Santé Ile De France (ARS-IDF)

Paris, FRANCE

Mai 2017 - Avr 2020

-   contribuer à faire évoluer les indicateurs de santé publique en France.
-   Promovoir l'intérêt des bases de données médico-administratives en épidémiologie.
-   Analyse de données épidémiologiques à partir de systeme natinonale des données de santé
-   Elaboration de diagnostics locaux de santé (communes, intercommunalités)
-   Appui méthodologique des agents et des collectivités locales pour la realisation d'etude enquête, observationnelle...

### Research Fellow

Centre de recherches politiques de Sciences Po (Sciences Po-CEVIPOF)

Paris, FRANCE

Mar 2015 - Avr 2017

-   Responsable de l'axe de recherche « Dynamique des zones critiques et conflits d'urbanisation» du programme « Politiques de la Terre » de Sorbonne Paris Cité (IDEX).

### Doctorant

Institut National de l'Environnement Industriel et des risques (Ineris)

Oise, FRANCE

Nov 2011 - Jan 2015

-   Caractérisation des inégalités territoriales, environnementales et sociales de santé
-   Développement d'un outil d'intégration des phénomènes spatiaux pour la construction d'indicateurs composites à l'échelle régionale

## Compétences {data-icon="laptop"}

### Statistique / Geostatistique

N/A

N/A

N/A

::: {.concise}
-   Exploitation des données de santé avec le SNDS: DCIR Simplifié -- DCIR, PMSi (MCO-SSR..), mortalité CePiDC (causes médicales de décès)
-   Statistiques spatiales/temporelles : modèles bayésiens, géostatistiques, multivariés, multiniveaux, analyses de survie, données longitudinales...
-   Croisement de données environnementales, socio-économiques et sanitaires (régression linéaire, multiniveaux, modèles mixtes, régression logistique, régression de Poisson...).
-   Intégration des phénomènes spatiaux dans le croisement (régression géographiquement pondérée, modèles d'auto- régression simultanée, de décalage spatial).
-   Conceptualisation, construction, combinaison et analyse d'indicateurs spatialisés.
-   Analyse multidimensionnelle de réduction de données, analyse factorielle, modèle hiérarchique, analyse en composante principale géographiquement pondérée...).
:::

### Data-analyst / Data-science

N/A

N/A

N/A

::: {.concise}
-   Nettoyage et manipulation des données (dplyr)
-   Data visualisation (ggplot2, plotly)
-   Dashboard (flexdashboard)
-   Reproductibilité et automatisation des rapports (rmarkdown, knitr, git, shiny)
-   Cartographie
:::

### Reporting

N/A

N/A

N/A

::: {.concise}
-   Rédaction du rapport d'analyses statistique
-   Création de support de présentation des résultats
-   Rédaction du chapitre d'analyses statistiques de publication
-   Vulgarisations des résultats sous forme de représentation graphique
:::

### Methodologie / Coordination / Supervision / Gestion

N/A

N/A

N/A

::: {.concise}
-   Rédaction des protocoles d'études
-   Mobilisation de bases de données
-   Gestion de projets complexes
-   Animation de groupe de travail
-   Organisation de séminaire
-   Gestion et suivi de contrats, conventions
-   Contribution a la recherche de nouveaux projets et des financements
-   Assurer la validation, la relecture et les corrections
-   Valorisation des travaux
:::

## Publications et communications {data-icon="file"}

### 

-   Diégo Antolinos-Basso, Nathalie Blanc, Jean Chiche, **Saib MS** et Flaminia Paddeu, « S'engager pour l'environnement dans le Grand Paris : territoires, politiques et inégalités », Cybergeo

N/A

### 

-   **Saib MS** (2017) Spatial Autocorrelation in Voting Turnout. J Biom Biostat 8:376. Doi: 10.4172/2155-6180.1000376.

N/A

### 

-   Caudeville J **Saib MS**, et al. Inégalités environnementales en France : de l'émergence de la thématique vers l'appropriation par la société civile. 84e Congrès de l'Association Canadienne Francophone du Savoir, 9-13 mai 2016, Montréal.

N/A

### 

-   **Saib MS**, Caudeville J, Carre F, Ganry O, Trugeon A, et al. Spatial Relationship Quantification between Environmental, Socioeconomic and Health Data at Different Geographic Levels. Int. J. Environ. Res. Public Health 2014, 11, 3765-3786.

N/A

### 

-   **Saib MS**, Caudeville J, Carre F, Ganry O, Trugeon A, et al. (2014). Noise Filtering Cancer Mortality Data for a Better Assessment of Health-Environment Relationships: Application to the Picardy Region. J Biomet Biostat 5:200. doi: 10.4172/2155- 6180.1000200.

N/A

### 

-   **Saib MS**, Caudeville J, Beauchamp M, Carré F, Ganry O, Trugeon A, Cicolella A : Building spatial composite indicators to analyze environmental health inequalities on a regional scale. Environ Health. 2015 Aug 21;14:68. doi: 10.1186/s12940-015-0054-3.

N/A

### 

-   **Saib MS**, Caudeville J, et al. Analyse Spatio-temporelle du lien Environnement-Cancer en Picardie (ASTEC-Picardie). Communication orale. Congrès national des ORS « L'observation, nouveau périmètre, nouveau enjeux », Bordeaux, France, 4 & 5 avril 2013.

N/A

### 

-   **Saib MS**, Caudeville J, et al Analyse Spatio-Temporelle du lien Environnement-Cancer en Picardie: 7ème Conférence Francophone d'Epidémiologie Clinique 16 et 17 mai, Paris.

N/A

### 

-   **Saib MS**, Ganry O et al. Tendances de l'incidence et de la mortalité par cancer dans le département de la Somme entre 1990-2009 Réunion du Groupe des Registres et d'Épidémiologistes de Langue Latine, Genève, mai 2014.

N/A

### 

-   **Saib MS**, Sabatier P et al. Etude épidémiologique comparée des lymphomes malins chez le chien et chez l'homme dans le département de l'Isère. 19ème Journées des Statisticiens des Centres de Lutte contre le Cancer 9-11 mai 2012, Lyon.

N/A
